[workspace]

members = [
  "sample-03-rs",
  "sample-04-rs",
  "sample-05-rs",
  "sample-06-rs",
  "sample-07-09-rs",
]
resolver = "2"

[profile.release]
codegen-units = 1
incremental = false
lto = "fat"
opt-level = 3
panic = "abort"
strip = true
