version: "3"
services:
  webauthn:
    image: jqtype/webauthn-sample:latest
    container_name: webauthn-sample
    ## Uncomment if you build by yourself
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    init: true
    restart: unless-stopped
    ports:
      - 8080:8080
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    env_file: .env
    environment:
      - LOG_LEVEL=debug # debug|info|warn|error
      - LOG_TO_FILE=true
      - HOST_USER=jun
      - HOST_UID=501
      - HOST_GID=501
    volumes:
      # Log Directory for the case of LOG_TO_FILE=true
      - ./log:/webauthn/log
